# How deep into the skill list do we want to go (sorted by value counts)
# This will establish the width of matrix input to the clustering
min_skill_depth = 5000
# How deep in the title list we want to to go (sorted by value counts)
# Dropping infrequent titles as a form of cleaning
min_title_depth = 1000
# Minimum number of skills a profile has to contain to included in the data
min_skill_length = 10
# Number of clusters to stop the clustering at
n_cluster_stop = 1
# List of "bad" job titles to drop from the data -- built by hand and should be subject to re-investigation
titles_to_drop = ["ceo",
                  "president",
                  "partner",
                  "manager",
                  "sales manager",
                  "operations manager",
                  "executive",
                  "executive director",
                  "vice president",
                  "owner",
                  "founder",
                  "supervisor",
                  "business owner",
                  "intern",
                  "internship",
                  "co-founder",
                  "consultant",
                  "director",
                  "general manager",
                  "office manager",
                  "research assistant",
                  "business owner",
                  "assistant manager",
                  "executive assistant",
                  "store manager",
                  "associate",
                  "project coordinator",
                  "project manager",
                  "owner/operator",
                  "owner / operator",
                  "owner / manager",
                  "owner/manager",
                  "branch manager",
                  "administrator",
                  "office administrator",
                  "managing directory",
                  "senior consultant",
                  "adjointe administrative",
                  "directeur",
                  "team lead",
                  "buyer",
                  "research associate",
                  "boss",
                  "directeur général",
                  "summer student",
                  "member",
                  "vp",
                  "retired",
                  "employee",
                  "stagiaire",
                  "aucun",
                  "président",
                  "présidente",
                  "vice-présidente",
                  "chef d'entreprise",
                  "phd candidate",
                  "directrice générale",
                  "superviseur",
                  "chargé de projet",
                  "propriétaire",
                  "retraite",
                  "retraité"]
